sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - if [ $TRAVIS_BRANCH = "master" ]; then docker build -t vyo2003/ubuntu-boost:latest .; fi
  - if [ $TRAVIS_BRANCH = "rolling" ]; then docker build -t vyo2003/ubuntu-boost:rolling .; fi
  - if [ $TRAVIS_BRANCH = "baseimage" ]; then docker build -t vyo2003/ubuntu-boost:baseimage .; fi

deploy:
  provider: script
  script: bash docker_push
