sudo: required

language: generic

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - test $TRAVIS_BRANCH = "master"  && docker build -t vyo2003/ubuntu-boost:latest . || true
  - test $TRAVIS_BRANCH = "rolling" && docker build -t vyo2003/ubuntu-boost:rolling . || true
  - test $TRAVIS_BRANCH = "baseimage" && docker build -t vyo2003/ubuntu-boost:baseimage . || true

deploy:
  provider: script
  script: bash docker_push
  on:
    branches:
      only:
        - master
        - rolling
        - baseimage
