#!/bin/bash
m4 -I . Dockerfile.m4 > Dockerfile

case $TRAVIS_BRANCH in
	master)
		docker build -t vyo2003/ubuntu-boost:latest .
		;;
	rolling)
		docker build -t vyo2003/ubuntu-boost:rolling .
		;;
	baseimage)
		docker build -t vyo2003/ubuntu-boost:latest .
		;;
esac
